apiVersion: sourceplane.io/v1
kind: ComponentTree
metadata:
    intent: /Users/irinelinson/sourceplane/multi-tenant-saas/intent.yaml
    generatedAt: "2026-05-11T09:55:05Z"
discovery:
    roots:
        - apps
        - infra
        - packages
        - tests
components:
    - name: api-edge
      type: cloudflare-worker-turbo
      domain: starter-runtime
      enabled: false
      path: apps/api-edge
      subscribe:
        environments:
            - dev
      inputs:
        buildCommand: pnpm exec turbo run build --filter=./
        nodeVersion: "22"
        pnpmVersion: 10.12.1
        productionBranch: main
        typecheckCommand: pnpm exec turbo run typecheck --filter=./
      dependsOn:
        - component: contracts-tests
          environment: ""
          scope: ""
          condition: success
      source: discovered
      sourcePath: apps/api-edge/component.yaml
      fileSize: 457
      fileModTime: "2026-05-11T09:54:36.549222284Z"
    - name: web-console
      type: cloudflare-pages-turbo
      domain: starter-ui
      enabled: false
      path: apps/web-console
      subscribe:
        environments:
            - dev
      inputs:
        buildCommand: pnpm exec turbo run build --filter=./
        nodeVersion: "20"
        outputDir: dist
        pnpmVersion: 10.12.1
        productionBranch: main
        projectName: sourceplane-web-console
      source: discovered
      sourcePath: apps/web-console/component.yaml
      fileSize: 380
      fileModTime: "2026-05-11T09:39:02.101109791Z"
    - name: infra-terraform-core
      type: terraform
      domain: starter-infra
      enabled: false
      path: infra/terraform/core
      subscribe:
        environments:
            - dev
      inputs:
        stackName: core
        terraformDir: infra/terraform/core
      labels:
        layer: infra
        provider: terraform
      dependsOn:
        - component: infra-terraform-state
          environment: ""
          scope: ""
          condition: success
      source: discovered
      sourcePath: infra/terraform/core/component.yaml
      fileSize: 373
      fileModTime: "2026-05-11T09:55:01.640397421Z"
    - name: infra-terraform-state
      type: terraform
      domain: starter-infra
      enabled: false
      path: infra/terraform/state
      subscribe:
        environments:
            - dev
      inputs:
        stackName: state
        terraformDir: infra/terraform/state
      labels:
        layer: infra
        provider: terraform
      source: discovered
      sourcePath: infra/terraform/state/component.yaml
      fileSize: 299
      fileModTime: "2026-05-11T09:55:01.63843247Z"
    - name: contracts
      type: turbo-package
      domain: starter-contracts
      enabled: false
      path: packages/contracts
      subscribe:
        environments:
            - dev
      inputs:
        buildCommand: pnpm exec turbo run build --filter=./
        nodeVersion: "20"
        pnpmVersion: 10.12.1
        typecheckCommand: pnpm exec turbo run typecheck --filter=./
      source: discovered
      sourcePath: packages/contracts/component.yaml
      fileSize: 352
      fileModTime: "2026-05-11T09:39:02.107788344Z"
    - name: shared
      type: turbo-package
      domain: starter-shared
      enabled: false
      path: packages/shared
      subscribe:
        environments:
            - dev
      inputs:
        buildCommand: pnpm exec turbo run build --filter=./
        nodeVersion: "20"
        pnpmVersion: 10.12.1
        typecheckCommand: pnpm exec turbo run typecheck --filter=./
      source: discovered
      sourcePath: packages/shared/component.yaml
      fileSize: 346
      fileModTime: "2026-05-11T09:39:02.109424431Z"
    - name: testing
      type: turbo-package
      domain: starter-shared
      enabled: false
      path: packages/testing
      subscribe:
        environments:
            - dev
      inputs:
        buildCommand: pnpm exec turbo run build --filter=./
        nodeVersion: "20"
        pnpmVersion: 10.12.1
        typecheckCommand: pnpm exec turbo run typecheck --filter=./
      labels:
        layer: test-utilities
      source: discovered
      sourcePath: packages/testing/component.yaml
      fileSize: 383
      fileModTime: "2026-05-11T09:39:02.111899581Z"
    - name: contracts-tests
      type: turbo-package
      domain: starter-tests
      enabled: false
      path: tests/contracts
      subscribe:
        environments:
            - dev
      inputs:
        buildCommand: pnpm exec turbo run build --filter=./
        nodeVersion: "20"
        pnpmVersion: 10.12.1
        preBuildCommand: pnpm exec turbo run test --filter=./
        typecheckCommand: pnpm exec turbo run typecheck --filter=./
      labels:
        layer: test
      source: discovered
      sourcePath: tests/contracts/component.yaml
      fileSize: 438
      fileModTime: "2026-05-11T09:39:02.1135905Z"
