apiVersion: sourceplane.io/v1
kind: Component
metadata:
  name: infra-terraform-state
spec:
  type: terraform
  domain: starter-infra
  subscribe:
    environments:
      - dev
  inputs:
    stackName: state
    terraformDir: .
  labels:
    layer: infra
    provider: terraform
