apiVersion: sourceplane.io/v1
kind: Component
metadata:
  name: infra-terraform-state
spec:
  type: turbo-package
  domain: starter-infra
  inputs:
    nodeVersion: "20"
  labels:
    layer: infra
    provider: terraform
