apiVersion: sourceplane.io/v1
kind: Component
metadata:
  name: infra-terraform-core
spec:
  type: terraform
  domain: starter-infra
  subscribe:
    environments:
      - name: dev
        profile: pull-request
      - name: staging
        profile: verify
      - name: production
        profile: release
  inputs:
    stackName: core
    terraformDir: .
  labels:
    layer: infra
    provider: terraform
  dependsOn:
    - component: infra-tf-state-r2
      condition: success
